# Backend Service
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: imdb-clone
    component: backend
    {{- include "imdb-clone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: imdb-clone
    component: backend
---
{{- end }}

# Backend Deployment
{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: imdb-clone
    component: backend
    {{- include "imdb-clone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: imdb-clone
      component: backend
  template:
    metadata:
      labels:
        app: imdb-clone
        component: backend
        {{- include "imdb-clone.labels" . | nindent 8 }}
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
          name: http
        env:
        {{- if .Values.backend.env }}
        {{- toYaml .Values.backend.env | nindent 8 }}
        {{- end }}
        {{- if .Values.global.environment }}
        - name: NODE_ENV
          value: {{ .Values.global.environment | quote }}
        {{- end }}
        {{- if .Values.mongodb.atlas.enabled }}
        - name: MONGODB_URI
          value: {{ .Values.mongodb.atlas.mongoUrl | quote }}
        {{- else if .Values.mongodb.enabled }}
        - name: MONGODB_URI
          value: "mongodb://mongodb:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database }}"
        {{- end }}
        - name: PORT
          value: {{ .Values.backend.service.targetPort | quote }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.healthCheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.healthCheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
---
{{- end }}