{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imdb-clone-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app: imdb-clone
    {{- include "imdb-clone.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxyBodySize | default "10m" | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.proxyConnectTimeout | default "30" | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.proxyReadTimeout | default "120" | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.proxySendTimeout | default "120" | quote }}
    {{- if .Values.ingress.cors.enabled }}
    # CORS configuration
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.ingress.cors.allowOrigin | quote }}
    nginx.ingress.kubernetes.io/cors-allow-methods: {{ .Values.ingress.cors.allowMethods | quote }}
    nginx.ingress.kubernetes.io/cors-allow-headers: {{ .Values.ingress.cors.allowHeaders | quote }}
    nginx.ingress.kubernetes.io/cors-allow-credentials: {{ .Values.ingress.cors.allowCredentials | quote }}
    {{- end }}
    {{- if .Values.ingress.customAnnotations }}
    {{- range $key, $value := .Values.ingress.customAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{- if .Values.backend.enabled }}
      # Backend API routes
      - path: {{ .Values.ingress.backend.path | default "/api/health" }}
        pathType: {{ .Values.ingress.backend.pathType | default "Prefix" }}
        backend:
          service:
            name: backend-service
            port:
              number: {{ .Values.backend.service.port }}
      {{- end }}
      {{- if .Values.frontend.enabled }}
      # Frontend routes - catch all other routes
      - path: {{ .Values.ingress.frontend.path | default "/" }}
        pathType: {{ .Values.ingress.frontend.pathType | default "Prefix" }}
        backend:
          service:
            name: frontend-service
            port:
              number: {{ .Values.frontend.service.port }}
      {{- end }}
{{- end }}