# MongoDB Secrets
{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mongodb
    component: database
    {{- include "imdb-clone.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  mongodb-root-user: {{ .Values.mongodb.auth.rootUser | b64enc }}
  mongodb-database: {{ .Values.mongodb.database | b64enc }}
  # Local MongoDB connection string
  MONGO_URL: {{ printf "mongodb://%s:%s@mongodb-service:%v/%s" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword .Values.mongodb.port .Values.mongodb.database | b64enc }}
---
{{- end }}

# MongoDB Atlas Secret (if using Atlas instead of local MongoDB)
{{- if .Values.mongodb.atlas.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    app: imdb-clone
    component: database
    {{- include "imdb-clone.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_URL: {{ .Values.mongodb.atlas.mongoUrl | b64enc }}
---
{{- end }}

# Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app: imdb-clone
    {{- include "imdb-clone.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ "your-jwt-secret-key-here" | b64enc }}
  API_KEY: {{ "your-api-key-here" | b64enc }}